/**
* Name: Zone02_simulation
* Based on the internal empty template. 
* Author: daan
* Tags: 
*/


model households_test


import "households_model.gaml"
//import "facilities_model.gaml"


global {
		
//	Time-related constants

	date starting_date <- date("2021-01-01 00:00:00");
	
	float step <- 10 #minutes;
	int cycles_in_hour <- 6;
	int cycles_in_day <- 24*6; 
	
//	Vital variables
	float alpha <- 0.1;
	float beta <- 1.0;
	float gamma <-1.0;
	float epsilon; // Not relevant 
	
//	Statistics
	list<float> average_emotional_states;
	
	init {
		
		csv_file f <- csv_file("fully_matrix.csv");
		matrix sn_matrix <- matrix(f);
				
		int nb_households<-10;
		
//		Create household agents
		create households number: nb_households{	
	
			// Constants
			ration <- 15.0; 				// kg rice / pers / day
//			home_location <- any;				// home location = current location 
			
//			Specific constants
			nb_members <- 5;
			pc<- 0.1;
			
			
//			Initialise variables	
			unsatisfied_consumption <- 0.0;
			unsatisfied_demand <- 0.0;
					
			food_storage <- 0;			// initial food storage 
			emotional_state <- 1.0;
			emotional_timestamp <- 0;
					
		}
		
//		Making the social network based on the imported sn_matrix		
		loop i from: 0 to: (nb_households-1) {			
			loop j from: 0 to: (nb_households-1) {					
				if int(sn_matrix[i,j]) = 1{			
					ask households[int(i)]{
						add households[j] to: social_network;	
						}
				} else{
				}
			}			
		}
	}
	
	reflex fetch_statistics {
		add households mean_of each.emotional_state to: average_emotional_states;		 
	}
	
}



experiment simple_simulation keep_seed: true type: gui {
 	parameter "Forgetting rate" var: alpha min: 0 max:1 step: 0.1;
 	parameter "Talkativity" var: beta min: 0 max:1 step: 0.1;
 	parameter "Size of security stock in days" var: gamma min: 0 max:30 step: 1;
	 
		
	output {
		
	display emotional_graphs {
       chart "Emotional state of all households" type: series y_label: "emotional state" y_range:[0,1] x_range: [0,5*cycles_in_day] size: {1.0,0.5} position: {0, 0.5}{
       loop hh over: households {
       		data hh.name value: hh.emotional_state;
        }
		}
       chart "Average emotional state over time" type: series y_label: "emotional state" y_range:[0,1] x_range: [0,5*cycles_in_day] size: {1.0,0.5} position: {0, 0}{
       data "Avg emo state" value: households mean_of each.emotional_state; 
		}		
	}
	
	display food_graphs {
       chart "Summed demand over time" type: series y_label: "demanded food" y_range:[0,1000] x_range: [0,5*cycles_in_day] size: {1.0,0.5} position: {0, 0}{
       data "sum food" value: households sum_of each.unsatisfied_demand; // unsatisfied demand as temporary container 
		}	
		chart "Summed food storage over time" type: series y_label: "food in storage" y_range:[0,1000] x_range: [0,5*cycles_in_day] size: {1.0,0.5} position: {0, 0.5}{
       data "sum food in storage" value: households sum_of each.food_storage; 
		}	
			
	}
    monitor "average emotional state" value: households mean_of each.emotional_state; 
    monitor "total demand" value: households sum_of each.food_demanded;
    }
}
    
//	monitor "Total food delivery gap" value: total_food_demanded-total_food_delivered;
//	monitor "Total hungry days" value: total_hungry_days;
	


// Make sure to have deleted the file result.txt in the model dir before running this experiment
// otherwise data is appended to data generated by the previous run. 
experiment batch_experiment type: batch repeat: 4 keep_seed: true until: ( cycle > 10*24*6 ) {

	parameter "Est. facility capacity per cycle" var: gamma min: 10 max: 100 step: 10;
//	parameter "Est. avg beneficiaries per building" var: gamma min: 0 max: 5 step: 1;



}












